toolpath example
Kinovarobotics/Kortex3 pull request #7
Opened 2024-02-26 20:47 UTC by KinoExpert

2024-02-26 21:10 UTC, martinleroux requested changes
Appliquer commentaires.

2024-02-26 21:10 UTC, martinleroux commented on api_python/102-Movement_high_level/07-Toolpath_trajectory.py
> +def populate_line_coordinates(waypointInformation):
changer "line" pour "segment"

2024-02-26 21:10 UTC, martinleroux commented on api_python/102-Movement_high_level/07-Toolpath_trajectory.py
> +    kTheta_x = 0.8
Mettons des coordonnées propres, genre 0, 180, 90.

2024-02-26 21:10 UTC, martinleroux commented on api_python/102-Movement_high_level/07-Toolpath_trajectory.py
> +    program_name = 'Newhome'
Tant qu'à ce qu'on fasse faire une trajectoire préprogrammée sur le robot, on peut bien utiliser le Home standard.

2024-02-26 21:10 UTC, martinleroux commented on api_python/102-Movement_high_level/07-Toolpath_trajectory.py
> +    waypointsDefinition = (
Ajouter un commentaire qui dit c'est quoi tous les paramètres à passer.

2024-02-26 21:10 UTC, martinleroux commented on api_python/102-Movement_high_level/07-Toolpath_trajectory.py
> +    wptlist.duration = 60 # in seconds
à enlever

2024-02-26 21:10 UTC, martinleroux commented on api_python/102-Movement_high_level/07-Toolpath_trajectory.py
> +        np.append(array_wpts, waypointsDefinition[i])
Voir ce qui se passe si on l'enlève.

2024-02-27 14:56 UTC, KinoExpert reviewed
changes have been applied

2024-03-05 20:02 UTC, martinleroux approved these changes

2024-03-05 20:04 UTC, merged